language: java
jdk:
- oraclejdk8
before_install: gem install bundler jekyll html-proofer
script: mvn -fae -U -B clean install -P check
after_success: 
- chmod +x .travis/deploy-docs.sh && .travis/deploy-docs.sh
- curl -Ls https://git.io/deploy-maven-snapshot | bash
env:
  global:
  - SNAPSHOT_BRANCH: "develop"
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # gh-pages: speeds up installation of html-proofer
cache:
  directories
  - $HOME/.m2
notifications:
  irc:
    channels:
    - "chat.freenode.net#52north"
    on_failure: always
